version: "3"
services:
    node:
        build:
            context: .
            dockerfile: "./Dockerfile"
        working_dir: /usr/src/app
        volumes:
            - .:/usr/src/app:cached
        command: tail -f /dev/null
